language: csharp
mono:
  - latest
solution: ./test/DuoApiTest.sln
install:
  - nuget restore ./test/DuoApiTest.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - msbuild ./test/DuoApiTest.sln