language: csharp
mono:
  - latest
solution: duo_api_csharp.sln
install:
  - nuget restore duo_api_csharp.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release duo_api_csharp.sln