matrix:
  include:
    - language: csharp
      solution: ./test/DuoApiTest.sln
      mono: none
      dotnet: 2.1.502
      install:
        - choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"
        - choco install dotnetcore-sdk
      script:
        - dotnet build ./test/DuoApiTest.sln